"""Measure detection delay, misses and false alarms of tp integrity on seeded synthetic runs, and write docs/results/integrity-validation.md.

Run from the repository root: python scripts/integrity_validation.py. The run series come from tests/support.py,
so the numbers describe the same generators the tests use.
"""

from __future__ import annotations

import argparse
import statistics
import sys
from collections.abc import Callable, Sequence
from pathlib import Path
from typing import Final

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tests.support import batched_series, mismatch_series  # noqa: E402
from tplane.integrity.monitor import (  # noqa: E402
    DEFAULT_INTEGRITY_OPTIONS,
    Alarm,
    Signal,
    detect_alarms,
)
from tplane.schema import Action, Record  # noqa: E402

SEEDS: Final[range] = range(50)
OUTPUT: Final[Path] = Path("docs/results/integrity-validation.md")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, allow_abbrev=False)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    arguments = parser.parse_args(argv)
    lines = [
        *_header(),
        *_failure_rate_section(),
        *_reward_section(),
        *_mismatch_section(),
        *_false_alarm_section(),
    ]
    arguments.output.write_text("\n".join(lines) + "\n")
    print(f"wrote {arguments.output}")
    return 0


UNITS_PER_STEP: Final[int] = 32
CHANGE_AT: Final[int] = 150


def _header() -> list[str]:
    options = DEFAULT_INTEGRITY_OPTIONS
    return [
        "# Integrity monitor validation",
        "",
        "@generated by scripts/integrity_validation.py. Do not edit by hand.",
        "",
        f"Method: {len(SEEDS)} seeds per row. The synthetic batched runs come from `tests/support.py` "
        "(`batched_series`: 8 prompts x 4 rollouts per step, prompt difficulty drawn around a pass rate that rises "
        "0.1 over the run, so rollouts of one prompt are correlated; `mismatch_series`). "
        f"Default `IntegrityOptions`: alarm_probability {options.alarm_probability}, hazard {options.hazard} per step, "
        f"failure rates {options.failure_rate_healthy}/{options.failure_rate_broken} with an estimated Rao-Scott design "
        f"effect, reward reference {options.reward_reference_steps} steps lagged {options.reward_lag_steps}, shift "
        f"{options.reward_shift_sd} unit sd, kl {options.healthy_kl}/{options.broken_kl}, ratio shift {options.ratio_shift}. "
        f"Delay is counted in steps from the first changed step ({CHANGE_AT}). A miss is no alarm before the run ends.",
        "",
        "These generators match the detector's assumptions except for the correlation and drift they add on purpose; "
        "they show the detector works as designed, not how it performs on a real run.",
        "",
    ]


def _failure_rate_section() -> list[str]:
    rows: list[tuple[str, ...]] = []
    for failure_rate in (0.05, 0.1, 0.2, 0.3, 0.5, 1.0):
        delays = _delays(
            lambda seed, rate=failure_rate: batched_series(
                seed=seed, infra_rate_after=rate, detected_action=Action.MASK
            ),
            Signal.FAILURE_RATE,
        )
        rows.append((f"{failure_rate:.2f}", *_summary(delays)))
    return _table(
        f"Failure-rate alarm after sandboxes start failing at step {CHANGE_AT} (typed, masked; 150 steps after the change)",
        ("failure rate after", "median delay (steps)", "90th percentile", "missed", "delays"),
        rows,
    )


def _reward_section() -> list[str]:
    scenarios: tuple[tuple[str, Callable[[int], list[Record]]], ...] = (
        (
            "50% sandbox failures, 70% of them untyped",
            lambda seed: batched_series(seed=seed, infra_rate_after=0.5, detected_fraction=0.3),
        ),
        (
            "30% sandbox failures, 70% of them untyped",
            lambda seed: batched_series(seed=seed, infra_rate_after=0.3, detected_fraction=0.3),
        ),
        (
            "50% sandbox failures, all untyped (not identifiable)",
            lambda seed: batched_series(seed=seed, infra_rate_after=0.5, detected_fraction=0.0),
        ),
        (
            "pass rate 0.5 -> 0.2, no infra change",
            lambda seed: batched_series(seed=seed, pass_rate_after=0.2),
        ),
        (
            "pass rate 0.5 -> 0.35, no infra change",
            lambda seed: batched_series(seed=seed, pass_rate_after=0.35),
        ),
    )
    rows: list[tuple[str, ...]] = []
    for name, build in scenarios:
        alarms = [_first(detect_alarms(build(seed)), Signal.REWARD) for seed in SEEDS]
        delays = [None if alarm is None else _step(alarm) - CHANGE_AT for alarm in alarms]
        verdicts = [
            alarm.attribution.verdict.value
            for alarm in alarms
            if alarm is not None and alarm.attribution is not None
        ]
        counts = ", ".join(
            f"{verdict} {verdicts.count(verdict)}" for verdict in sorted(set(verdicts))
        )
        rows.append((name, *_summary(delays)[:3], counts))
    return _table(
        f"Reward alarm and its attribution after a change at step {CHANGE_AT} (150 steps after the change)",
        ("scenario", "median delay (steps)", "90th percentile", "missed", "verdicts"),
        rows,
    )


def _mismatch_section() -> list[str]:
    rows: list[tuple[str, ...]] = []
    cases: tuple[tuple[str, float, float], ...] = (
        ("kl 4e-4 -> 5e-3", 5e-3, 1.0),
        ("kl 4e-4 -> 1e-2", 1e-2, 1.0),
        ("kl 4e-4 -> 3e-2", 3e-2, 1.0),
        ("kl 4e-4 -> 1e-1", 1e-1, 1.0),
        ("mean ratio 1 -> 0.995", 4e-4, 0.995),
        ("mean ratio 1 -> 0.99", 4e-4, 0.99),
        ("mean ratio 1 -> 0.97", 4e-4, 0.97),
    )
    for name, kl_after, ratio_after in cases:
        alarms = [
            _first(
                detect_alarms(
                    mismatch_series(
                        seed=seed,
                        steps=100,
                        change_at=50,
                        kl_after=kl_after,
                        ratio_after=ratio_after,
                    )
                ),
                Signal.MISMATCH,
            )
            for seed in SEEDS
        ]
        delays = [
            None if alarm is None else (int(alarm.unit_id.split("-")[1]) - 5) // 10 - 50
            for alarm in alarms
        ]
        rows.append((name, *_summary(delays)))
    return _table(
        "Mismatch alarm after a change at train step 50 (50 steps after the change; ratio standard error 0.002)",
        ("change", "median delay (steps)", "90th percentile", "missed", "delays"),
        rows,
    )


def _false_alarm_section() -> list[str]:
    steps = 1_000
    scenarios: tuple[tuple[str, Callable[[int], list[Record]]], ...] = (
        (
            "healthy, correlated prompts, learning drift",
            lambda seed: batched_series(seed=seed, steps=steps, change_at=10**9),
        ),
        (
            "healthy, one prompt group fails every 4th step",
            lambda seed: batched_series(seed=seed, steps=steps, change_at=10**9, burst_every=4),
        ),
        (
            "healthy mismatch, kl 4e-4",
            lambda seed: mismatch_series(seed=seed, steps=steps, stride=UNITS_PER_STEP),
        ),
    )
    rows = []
    for name, build in scenarios:
        counts: dict[Signal, int] = {signal: 0 for signal in Signal}
        for seed in SEEDS:
            for alarm in detect_alarms(build(seed)):
                counts[alarm.signal] += 1
        rows.append((name, f"{steps * len(SEEDS):,}", *[str(counts[signal]) for signal in Signal]))
    return _table(
        f"False alarms on runs with no change ({len(SEEDS)} seeds x {steps:,} steps per scenario)",
        ("scenario", "steps scanned", *[f"{signal.value} alarms" for signal in Signal]),
        rows,
    )


def _delays(build: Callable[[int], list[Record]], signal: Signal) -> list[int | None]:
    alarms = [_first(detect_alarms(build(seed)), signal) for seed in SEEDS]
    return [None if alarm is None else _step(alarm) - CHANGE_AT for alarm in alarms]


def _first(alarms: Sequence[Alarm], signal: Signal) -> Alarm | None:
    matching = [alarm for alarm in alarms if alarm.signal is signal]
    return matching[0] if len(matching) != 0 else None


def _step(alarm: Alarm) -> int:
    return int(alarm.unit_id.split("-")[1]) // UNITS_PER_STEP


def _summary(delays: Sequence[int | None]) -> tuple[str, str, str, str]:
    found = sorted(delay for delay in delays if delay is not None)
    missed = len(delays) - len(found)
    if len(found) == 0:
        return ("-", "-", f"{missed}/{len(delays)}", "")
    percentile = found[min(len(found) - 1, int(0.9 * len(found)))]
    raw = " ".join("miss" if delay is None else str(delay) for delay in delays)
    return (f"{statistics.median(found):g}", str(percentile), f"{missed}/{len(delays)}", raw)


def _table(title: str, columns: tuple[str, ...], rows: Sequence[tuple[str, ...]]) -> list[str]:
    return [
        f"## {title}",
        "",
        "| " + " | ".join(columns) + " |",
        "|" + "---|" * len(columns),
        *["| " + " | ".join(row) + " |" for row in rows],
        "",
    ]


if __name__ == "__main__":
    raise SystemExit(main())
